### ISSUE TITLE
`glisten.send()` using deprecated `BytesBuilder` type

### ISSUE THREAD

**Issue by Suguis** [rawhat/glisten#25]
First of all, wanted to say hi  :wave:. I'm pretty new to the Gleam community and language, and quite new to contributing to open source in general. So feedback is appreciated.

I use glisten for a project. When updating to stdlib `0.42.0`, I noticed that the `bytes_builder` module was deprecated in favor of the `bytes_tree` module. This is a simple name change due to usage confusion because of the "builder" prefix, see https://github.com/gleam-lang/stdlib/pull/737.

The problem is that `glisten.send()` needs a param of the deprecated type `BytesBuilder`. So that function will need to accept a `BytesTree` instead. Also, there are also some deprecated functions used out there in the code (like `result.nil_error`).

If it's not a problem, I could do a PR to fix these deprecations. I think it's easy to do it since the changes are small and trivial. Thanks!

**Comment by rawhat** [comment]
Thank you for the interest!  My apologies, but I did already update this.  I'll need to do a version release, and I suspect your code might still warn because the `gleam/bytes_builder` module still exists and references itself.

Didn't mean to take the contribution from you!  Welcome to Gleam and hope you enjoy your time 😄

**Comment by Suguis** [comment]
Don't worry, glad to know it's already taken in account for next release. Thank you :)
